### ISSUE TITLE
CLI broken

### ISSUE THREAD

**Issue by ibevers** [sensein/b2aiprep#92]
```
(.venv) isaacbevers@MacBook-Pro-87 b2aiprep % b2aiprep-cli --help                                     
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 28.2M/28.2M [00:02<00:00, 10.0MB/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████▉| 360M/360M [00:41<00:00, 9.07MB/s]
Traceback (most recent call last):
  File "/Users/isaacbevers/sensein/b2ai-wrapper/.venv/bin/b2aiprep-cli", line 5, in <module>
    from b2aiprep.cli import cli
  File "/Users/isaacbevers/sensein/b2ai-wrapper/b2aiprep/src/b2aiprep/cli.py", line 8, in <module>
    from b2aiprep.commands import (  # gensynthtabdata,
  File "/Users/isaacbevers/sensein/b2ai-wrapper/b2aiprep/src/b2aiprep/commands.py", line 47, in <module>
    from b2aiprep.prepare.prepare import extract_features_workflow, validate_bids_data
  File "/Users/isaacbevers/sensein/b2ai-wrapper/b2aiprep/src/b2aiprep/prepare/prepare.py", line 49, in <module>
    from senselab.audio.tasks.features_extraction.api import extract_features_from_audios
  File "/Users/isaacbevers/sensein/b2ai-wrapper/.venv/lib/python3.10/site-packages/senselab/audio/tasks/features_extraction/api.py", line 16, in <module>
    from .torchaudio_squim import extract_objective_quality_features_from_audios
  File "/Users/isaacbevers/sensein/b2ai-wrapper/.venv/lib/python3.10/site-packages/senselab/audio/tasks/features_extraction/torchaudio_squim.py", line 11, in <module>
    subjective_model = SQUIM_SUBJECTIVE.get_model()
  File "/Users/isaacbevers/sensein/b2ai-wrapper/.venv/lib/python3.10/site-packages/torchaudio/pipelines/_squim_pipeline.py", line 129, in get_model
    state_dict = torch.load(path, weights_only=True)
  File "/Users/isaacbevers/sensein/b2ai-wrapper/.venv/lib/python3.10/site-packages/torch/serialization.py", line 1326, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/Users/isaacbevers/sensein/b2ai-wrapper/.venv/lib/python3.10/site-packages/torch/serialization.py", line 671, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
(.venv) isaacbevers@MacBook-Pro-87 b2aiprep % b2aiprep-cli --help
Traceback (most recent call last):
  File "/Users/isaacbevers/sensein/b2ai-wrapper/.venv/bin/b2aiprep-cli", line 5, in <module>
    from b2aiprep.cli import cli
  File "/Users/isaacbevers/sensein/b2ai-wrapper/b2aiprep/src/b2aiprep/cli.py", line 8, in <module>
    from b2aiprep.commands import (  # gensynthtabdata,
  File "/Users/isaacbevers/sensein/b2ai-wrapper/b2aiprep/src/b2aiprep/commands.py", line 47, in <module>
    from b2aiprep.prepare.prepare import extract_features_workflow, validate_bids_data
  File "/Users/isaacbevers/sensein/b2ai-wrapper/b2aiprep/src/b2aiprep/prepare/prepare.py", line 49, in <module>
    from senselab.audio.tasks.features_extraction.api import extract_features_from_audios
  File "/Users/isaacbevers/sensein/b2ai-wrapper/.venv/lib/python3.10/site-packages/senselab/audio/tasks/features_extraction/api.py", line 16, in <module>
    from .torchaudio_squim import extract_objective_quality_features_from_audios
  File "/Users/isaacbevers/sensein/b2ai-wrapper/.venv/lib/python3.10/site-packages/senselab/audio/tasks/features_extraction/torchaudio_squim.py", line 11, in <module>
    subjective_model = SQUIM_SUBJECTIVE.get_model()
  File "/Users/isaacbevers/sensein/b2ai-wrapper/.venv/lib/python3.10/site-packages/torchaudio/pipelines/_squim_pipeline.py", line 129, in get_model
    state_dict = torch.load(path, weights_only=True)
  File "/Users/isaacbevers/sensein/b2ai-wrapper/.venv/lib/python3.10/site-packages/torch/serialization.py", line 1326, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/Users/isaacbevers/sensein/b2ai-wrapper/.venv/lib/python3.10/site-packages/torch/serialization.py", line 671, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory




```

**Comment by ibevers** [comment]
Hi @fabiocat93, this is not a blocker at the moment, but I will loop back and give more detail if it becomes one. Thank you for being willing to help!
